# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'pim/kimap' : '@same'
    'pim/kmailtransport' : '@same'
    'pim/kpimtextedit' : '@same'
    'pim/libksieve' : '@same'
    'pim/pimcommon' : '@same'
    'third-party/qtkeychain': '@latest'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]      
